package com.udacity.asteroidradar

object Constants {
    const val API_QUERY_DATE_FORMAT = "yyyy-MM-dd"
    const val DEFAULT_END_DATE_DAYS = 7
    const val BASE_URL = "https://api.nasa.gov"
    // my api key generated by nasa api
    const val API_KEY = "rATddM2rV8arWzFv26AKgySyZz9tfTjex55BSST2"
}